gitserver:
  port: 0

spring:
  application:
    name: auth-service

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

app:
  cors:
    # NO te autorreferencies; usa una env CORS_ALLOWED_ORIGINS o fallback
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:5173}
  firebase:
    enabled: true
    # tu código lee ESTE campo
    project-id: ${FIREBASE_PROJECT_ID_AUTH}
    credentials-file: ${FIREBASE_SECRETS_DIR}/subastasmax-auth.json
    # opcional: si quieres forzar archivo en vez de ADC
    # credentials-file: ${GOOGLE_APPLICATION_CREDENTIALS}
