services:
  config-server:
    build: ./config-server
    container_name: config-server
    ports: ["${CONFIG_PORT}:8888"]
    volumes:
      - ./config-repo:/config-repo:ro
    networks:
      - subastas-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

  discovery-service:
    build: ./discovery-service
    container_name: discovery-service
    ports: ["${DISCOVERY_PORT}:8761"]
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:${CONFIG_SERVER_URL}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
    networks:
      - subastas-network
    depends_on:
      config-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports: ["${GATEWAY_PORT}:8080"]
    environment:
      - CONFIG_SERVER_URL=${CONFIG_SERVER_URL}
      - EUREKA_DEFAULT_ZONE=${EUREKA_DEFAULT_ZONE}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS_CONTAINER}
    volumes:
      - ${FIREBASE_SECRETS_HOST_PATH}:${GOOGLE_APPLICATION_CREDENTIALS_CONTAINER}:ro
    networks:
      - subastas-network
    depends_on:
      config-server:
        condition: service_healthy
      discovery-service:
        condition: service_healthy
    restart: on-failure

  a-service:
    build: ./A-service
    container_name: A-service
    environment:
      - CONFIG_SERVER_URL=${CONFIG_SERVER_URL}
      - EUREKA_DEFAULT_ZONE=${EUREKA_DEFAULT_ZONE}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS_CONTAINER}
    volumes:
      - ${FIREBASE_SECRETS_HOST_PATH}:${GOOGLE_APPLICATION_CREDENTIALS_CONTAINER}:ro
    networks:
      - subastas-network
    depends_on:
      config-server:
        condition: service_healthy
      discovery-service:
        condition: service_healthy
    restart: on-failure

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "8081:8081"
    env_file:
      - ./auth-service/.env
    environment:
      - CONFIG_SERVER_URL=${CONFIG_SERVER_URL}
      - EUREKA_DEFAULT_ZONE=${EUREKA_DEFAULT_ZONE}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - FIREBASE_SECRETS_DIR=${FIREBASE_SECRETS_DIR_CONTAINER}
      - SERVER_PORT=8081
    volumes:
      - ${FIREBASE_SECRETS_DIR_HOST}:${FIREBASE_SECRETS_DIR_CONTAINER}:ro
    networks:
      - subastas-network
    depends_on:
      config-server:
        condition: service_healthy
      discovery-service:
        condition: service_healthy
    restart: on-failure




  bidding-service:
    build: ./bidding-service
    container_name: bidding-service
    ports:
      - "8090:8090"
    environment:
      - CONFIG_SERVER_URL=${CONFIG_SERVER_URL}
      - EUREKA_DEFAULT_ZONE=${EUREKA_DEFAULT_ZONE}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS_CONTAINER}
    volumes:
      - ${FIREBASE_SECRETS_HOST_PATH}:${GOOGLE_APPLICATION_CREDENTIALS_CONTAINER}:ro
    networks:
      - subastas-network
    depends_on:
      config-server:
        condition: service_healthy
      discovery-service:
        condition: service_healthy
      auth-service:
        condition: service_started
    restart: on-failure



  admin-service:
    build: ./admin-service
    container_name: admin-service
    environment:
      - CONFIG_SERVER_URL=${CONFIG_SERVER_URL}
      - EUREKA_DEFAULT_ZONE=${EUREKA_DEFAULT_ZONE}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS_CONTAINER}
    volumes:
      - ${FIREBASE_SECRETS_HOST_PATH}:${GOOGLE_APPLICATION_CREDENTIALS_CONTAINER}:ro
    networks:
      - subastas-network
    depends_on:
      config-server:
        condition: service_healthy
      discovery-service:
        condition: service_healthy
      auth-service:
        condition: service_started
    restart: on-failure


networks:
  subastas-network:
    driver: bridge