spring:
  application:
    name: api-gateway
  config:
    import: 'optional:configserver:${CONFIG_SERVER_URL:http://config-server:8888}'

  cloud:
    gateway:
      routes:
        - id: auth
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
        - id: admin-users
          uri: lb://auth-service
          predicates:
            - Path=/admin/**
        - id: bidding-ws
          uri: http://bidding-service:8090
          predicates:
            - Path=/bidding-ws/**
        - id: auctions
          uri: lb://auction-service
          predicates:
            - Path=/api/auctions/**
        - id: wallets
          uri: lb://wallet-service
          predicates:
            - Path=/api/wallets/**
        - id: transactions
          uri: lb://wallet-service
          predicates:
            - Path=/api/transactions/**
        - id: chat-ws
          uri: http://chat-service:8070
          predicates:
          - Path=/chat-ws/**


      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - http://localhost:3000
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowedHeaders:
              - Authorization
              - Content-Type
              - X-Requested-With
              - Accept
              - Origin
            exposedHeaders:
              - "*"
            allowCredentials: false
            maxAge: 3600

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://discovery-service:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include: health,info