spring:
  application:
    name: api-gateway
  config:
    import: 'optional:configserver:${CONFIG_SERVER_URL:http://config-server:8888}'
  cloud:
    gateway:
      routes:
        - id: auth
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
        - id: admin-users
          uri: http://admin-service:8070  # ← Puerto 8070
          predicates:
            - Path=/admin/**
          filters:
            - RewritePath=/admin/(?<segment>.*), /$\{segment}
        - id: bidding-ws
          uri: http://bidding-service:8090
          predicates:
            - Path=/bidding-ws/**

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://discovery-service:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include: health,info