spring:
  application:
    name: api-gateway
  config:
    import: 'optional:configserver:${CONFIG_SERVER_URL:http://config-server:8888}'
  cloud:
    gateway:
      routes:
        - id: auth
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
        - id: admin-users
          uri: lb://auth-service
          predicates:
            - Path=/admin/**
        - id: admin-service
          uri: lb://admin-service
          predicates:
            - Path=/admin/**
          filters:
            # eliminar el segmento /admin antes de enviar al admin-service
            - StripPrefix=1

        - id: notification-service
          uri: http://notification-service:8060
          predicates:
            - Path=/api/notifications/**

        - id: bidding-ws
          uri: http://bidding-service:8090
          predicates:
            - Path=/bidding-ws/**

        - id: auctions
          uri: lb://auction-service
          predicates:
            - Path=/api/auctions/**
        - id: transactions
          uri: lb://wallet-service
          predicates:
            - Path=/api/transactions/**
        - id: wallets
          uri: lb://wallet-service
          predicates:
            - Path=/api/wallets/**

        - id: wallet-transactions
          uri: lb://wallet-service
          predicates:
            - Path=/api/transactions/**

        - id: wallet-exchange-rates
          uri: lb://wallet-service
          predicates:
            - Path=/api/exchange-rates/**

      # Global CORS configuration (single, coherent block)
      globalcors:
        - id: all
          allowedOrigins:
            - ${NEXT_PUBLIC_API_BASE:http://localhost:8080}
            - "http://localhost:3000"
            - "http://127.0.0.1:3000"
          allowedMethods:
            - GET
            - POST
            - PUT
            - DELETE
            - PATCH
            - OPTIONS
          allowedHeaders:
            - Authorization
            - Content-Type
            - X-Requested-With
            - Accept
            - Origin
          exposedHeaders:
            - "*"
          allowCredentials: true
          maxAge: 3600

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://discovery-service:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include: health,info