spring:
  application:
    name: wallet-service1
  config:
    # Usa el Config Server si está; si no, sigue (no falla)
    import: 'optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}'

auth:
  service:
    url: http://localhost:8080
  

eureka:
  client:
    serviceUrl:
      # En local usa localhost; en docker puedes sobreescribir por ENV
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka}

firebase:
  database:
    url: https://wallet-service-7ce34.firebaseio.com
  config:
    path: classpath:firebase-service-account.json

logging:
  level:
    root: INFO
    com.google: DEBUG
    com.google.api.gax: DEBUG
    io.grpc: DEBUG
    SubastasMax: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

management.endpoints.web.exposure.include: health,info
