spring:
  application:
    name: wallet-service1
  config:
    # Usa el Config Server si está; si no, sigue (no falla)
    import: 'optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}'
  

eureka:
  client:
    serviceUrl:
      # En local usa localhost; en docker puedes sobreescribir por ENV
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka}

firebase:
  database:
    url: https://wallet-service-7ce34.firebaseio.com
  config:
    path: classpath:firebase-service-account.json

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

management.endpoints.web.exposure.include: health,info
