spring:
  application:
    name: chat-service
  cloud:
    config:
      enabled: false
      import-check:
        enabled: false

server:
  port: 8090

eureka:
  client:
    enabled: false

logging:
  level:
    root: INFO
